### ISSUE TITLE
Wavesurfer.js downloads whole episode via fetch to process WebAudio

### ISSUE THREAD

**Issue by Frando** [openaudiosearch/openaudiosearch#21]
The Wavesurfer.js player gives nice waveforms, but has a few issues at the moment:
- It needs to download the whole episode before the waveform is generated
- client-side waveform generation is quite expensive especially for lower-powered devices
- We need a proxy server, because waveform.js downloads via `fetch` (does not use audio elements) and that has CORS issues with remote servers usually.

Wavesurfer.js can also use server generated waveforms. That's nice but also we don't want to depend on waveforms having been generated for the audio player to work.

Let's look if we can either
a) make waveform display optional and see again if wavesurfer.js supports playback via audio elements
b) create our own player
c) use some other player library

Likely we will want a customized display soon anyway to display search terms in the timeline.

**Comment by dryptomim** [comment]
https://github.com/bbc/peaks.js#generating-waveform-data

**Comment by Frando** [comment]
#23 adds a new player, this can be closed if we go forward with the approach in #23.
