### ISSUE TITLE
Fix index settings: German stemming, case insensitivity

### ISSUE THREAD

**Issue by Frando** [openaudiosearch/openaudiosearch#35]
**Describe the bug**
The search
* is case sensitive (oh no!)
* has no german stemming

**Comment by hng** [comment]
Stemming needs to be changed in the settings part of the mapping which is defined here: https://github.com/openaudiosearch/openaudiosearch/blob/38e68dd99e4d9428f41ee38c8826dc922336b69b/rust/oas-core/src/index/elastic.rs#L518
