### ISSUE TITLE
remove unused oas.log from worker:codebase

### ISSUE THREAD

**Issue by viisauksena** [openaudiosearch/openaudiosearch#44]
**Describe the bug**
there is a file oas/oas.log generated by default - seems like a relikt

**To Reproduce**
vanilla install docker openaudiosearch

**Expected behavior**
remove oas.log from codebase or make log logging

see : https://github.com/openaudiosearch/openaudiosearch/blob/0c157093d9bfc0b13ee6214a88fc9fd0a64418fb/oas_worker/app/logging.py#L27

**Comment by Frando** [comment]
#37 will enable the worker logfile again

**Comment by Frando** [comment]
This was fixed with #37
