### ISSUE TITLE
push vosk de model to 21

### ISSUE THREAD

**Issue by viisauksena** [openaudiosearch/openaudiosearch#47]
actually vosk model de 6 is used, 
push it to vosk-model-de-0.21 (latest by now) and use it as default in worker:config

https://alphacephei.com/vosk/models
https://alphacephei.com/vosk/models/vosk-model-de-0.21.zip

**Comment by viisauksena** [comment]
see : pr https://github.com/openaudiosearch/openaudiosearch/pull/51

**Comment by Frando** [comment]
fixed in #51
