### ISSUE TITLE
Delete RSS Feed from Importer

### ISSUE THREAD

**Issue by datadonK23** [openaudiosearch/openaudiosearch#56]
**Is your feature request related to a problem? Please describe.**
In case you don't wanna follow a RSS feed any more, you want to delete it as a source of input. 

**Describe the solution you'd like**
Button in UI (Importer tab -> Feeds section), which deletes the listed RSS feed. 

**Describe alternatives you've considered**
\-

**Additional context**
Good to have in Dev phase and necessary in productional use.

**Comment by Frando** [comment]
Fixed in #57
